import importlib.util
import os
from pathlib import Path

import paraview.simple as pvs

# Load export.py directly — avoids importing anno/__init__.py (which needs treeparse)
# Path passed via env var because __file__ is not set when run via --pyscript
_export_py = Path(os.environ["ANNO_EXPORT_PY"])
_spec = importlib.util.spec_from_file_location("anno_pv_export", _export_py)
_mod = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_mod)
anno_export_selection = _mod.anno_export_selection

# Open mesh files passed via env var (colon-separated)
mesh_files = os.environ.get("ANNO_MESH_FILES", "")
for mesh_file in filter(None, mesh_files.split(":")):
    pvs.OpenDataFile(mesh_file, registrationName=Path(mesh_file).stem)
    pvs.Show()
pvs.ResetCamera()
pvs.Render()

# Auto-install macro into ParaView's user Macros folder (zero GUI steps)
macros_dir = Path.home() / ".config" / "ParaView" / "Macros"
macros_dir.mkdir(parents=True, exist_ok=True)
macro_file = macros_dir / "Anno_Export_Selection.py"

if not macro_file.exists():
    macro_file.write_text(f"""\
# Auto-generated by Anno — do not edit manually
import importlib.util
from pathlib import Path
_spec = importlib.util.spec_from_file_location("anno_pv_export", r"{_export_py}")
_mod = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_mod)
_mod.anno_export_selection()
""")
    print("Anno export macro installed automatically!")
else:
    print("Anno export macro already installed.")

print("-> Macros menu -> Anno_Export_Selection")
print("   (assign Ctrl+Shift+N once via Tools -> Customize Shortcuts)")
