import importlib.util
import os
from pathlib import Path

import paraview.simple as pvs

# Load export.py directly — avoids importing anno/__init__.py (which needs treeparse)
# Path passed via env var because __file__ is not set when run via --pyscript
_export_py = Path(os.environ["ANNO_EXPORT_PY"])
_spec = importlib.util.spec_from_file_location("anno_pv_export", _export_py)
_mod = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_mod)
anno_export_selection = _mod.anno_export_selection

# Open mesh files passed via env var (colon-separated)
mesh_files = os.environ.get("ANNO_MESH_FILES", "")
for mesh_file in filter(None, mesh_files.split(":")):
    pvs.OpenDataFile(mesh_file, registrationName=Path(mesh_file).stem)
    pvs.Show()
pvs.ResetCamera()
pvs.Render()

# Auto-install macros into ParaView's user Macros folder (zero GUI steps)
macros_dir = Path.home() / ".config" / "ParaView" / "Macros"
macros_dir.mkdir(parents=True, exist_ok=True)


def _install_macro(macro_name, func_name):
    macro_file = macros_dir / f"{macro_name}.py"
    macro_body = f"""\
# Auto-generated by Anno — do not edit manually
import importlib.util
from pathlib import Path
_spec = importlib.util.spec_from_file_location("anno_pv_export", r"{_export_py}")
_mod = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_mod)
_mod.{func_name}()
"""
    current = macro_file.read_text() if macro_file.exists() else None
    if current != macro_body:
        macro_file.write_text(macro_body)
        print(f"Anno macro (re)installed: {macro_name}")
    else:
        print(f"Anno macro already up to date: {macro_name}")


_install_macro("Anno_Export_Selection", "anno_export_selection")
_install_macro("Anno_Array_Comment", "anno_array_comment")

print("-> Macros menu -> Anno_Export_Selection / Anno_Array_Comment")
print("   (assign shortcuts once via Tools -> Manage Custom Shortcuts)")
print("   suggested: Ctrl+Shift+N = export, Ctrl+Shift+M = array comment")
